import { BuildingType, BuildingSpecialty } from '../../types/buildings';
import { ResourceType } from '../../types/terrain';
import type { BuildingConfig } from './index';

export const factoryConfigs: Record<string, BuildingConfig> = {
  [BuildingType.SMELTER]: {
    name: 'Iron Smelter',
    description: 'Smelts iron ore into iron plates',
    color: '#FF4500',
    icon: '🔥',
    inputs: { [ResourceType.IRON_ORE]: 2 },
    outputs: { [ResourceType.IRON_PLATE]: 1 },
    cost: { stone: 10, [ResourceType.IRON_ORE]: 5 },
    specialty: BuildingSpecialty.FACTORY,
    inventoryCapacity: 10,
    energyConsumption: 2,
  },
  [BuildingType.COPPER_SMELTER]: {
    name: 'Copper Smelter',
    description: 'Smelts copper ore into copper plates',
    color: '#DAA520',
    icon: '🔥',
    inputs: { [ResourceType.COPPER_ORE]: 2 },
    outputs: { [ResourceType.COPPER_PLATE]: 1 },
    cost: { stone: 10, [ResourceType.COPPER_ORE]: 5 },
    specialty: BuildingSpecialty.FACTORY,
    inventoryCapacity: 10,
    energyConsumption: 2,
  },
  [BuildingType.STEEL_FURNACE]: {
    name: 'Steel Furnace',
    description: 'Smelts iron plates and coal into steel plates',
    color: '#708090',
    icon: '🔥',
    inputs: { [ResourceType.IRON_PLATE]: 1, 'coal': 1 },
    outputs: { [ResourceType.STEEL_PLATE]: 1 },
    cost: { stone: 20, [ResourceType.IRON_PLATE]: 10, 'coal': 10 },
    specialty: BuildingSpecialty.FACTORY,
    inventoryCapacity: 10,
    energyConsumption: 2,
  },
  [BuildingType.ASSEMBLER]: {
    name: 'Iron Gear Assembler',
    description: 'Assembles iron plates into iron gears',
    color: '#4169E1',
    icon: '⚙️',
    inputs: { [ResourceType.IRON_PLATE]: 2 },
    outputs: { [ResourceType.IRON_GEAR]: 1 },
    cost: { stone: 10, [ResourceType.IRON_PLATE]: 10 },
    specialty: BuildingSpecialty.FACTORY,
    inventoryCapacity: 10,
    energyConsumption: 2,
  },
  [BuildingType.STEEL_ASSEMBLER]: {
    name: 'Steel Gear Assembler',
    description: 'Assembles steel plates into steel gears',
    color: '#2F4F4F',
    icon: '⚙️',
    inputs: { [ResourceType.STEEL_PLATE]: 2 },
    outputs: { [ResourceType.STEEL_GEAR]: 1 },
    cost: { stone: 15, [ResourceType.STEEL_PLATE]: 5 },
    specialty: BuildingSpecialty.FACTORY,
    inventoryCapacity: 10,
    energyConsumption: 2,
  },
};
